### ISSUE TITLE
Tell me how to demo the app in the README.md

### ISSUE THREAD

**Issue by jarodreyes** [TwilioDevEd/employee-directory-rails#2]
Add a new header:

## To Demo:
* Text your twilio number the name "Williams"
* Should get the following response: <screenshot>

or something like this.

**Comment by acamino** [comment]
@jarodreyes I added the [To Demo](https://github.com/TwilioDevEd/employee-directory-rails#to-demo) section in 92b6ee9 as you requested.

**Comment by mcelicalderon** [comment]
Done
