### ISSUE TITLE
Should be able to handle multiple partial matches.

### ISSUE THREAD

**Issue by jarodreyes** [TwilioDevEd/employee-directory-rails#4]
Appears EmployeeFinder does not handle multipl partial matches well... if there are multiple matches we should probably use an ordered array as the cookie hash, then in the return message:

"WE found multiple people, press (1) for Andy Williams (2) Bob Williams (3) William Colt." Then we can return the match that is [n] index in the cookie.

**Comment by acamino** [comment]
@jarodreyes please have a look at https://www.pivotaltracker.com/story/show/115035991, the last task mention that:

- [x] If partial match occurs send *FULL NAME* highest matching possibility.

Should we update the acceptance criteria of this particular story to match the new requirement?

If this is the case, I think we can use the current Twilio cookies approach without modification. And use the `Body` parameter to capture the client response, what do you think?

**Comment by jarodreyes** [comment]
Yeah we should update the story to match the new requirement. It is only useful is a large company like coca cola can send the closest options (possibly with paging) back to the user.

**Comment by acamino** [comment]
@jarodreyes this requirement was addressed here 2a72021, would you mind having a look at it please?

_Note: The subsequent commits are refactors to improve the readability of the solution._

**Comment by mcelicalderon** [comment]
Done
