### ISSUE TITLE
Use Marvel API for employee names

### ISSUE THREAD

**Issue by jarodreyes** [TwilioDevEd/employee-directory-rails#6]
Can even just replace seeds.rb with marvel characters. This is what @dprothero used in https://github.com/TwilioDevEd/employee-directory-csharp. If you have any questions I'm sure he'd be glad to share details on the implementation.

**Comment by acamino** [comment]
@jarodreyes I made the requested changes. Thanks for the suggestion, work with Marvel characters is so much fun.

Please have a look at the commits 49d2f27, ad55ee0, and 005bf9a.

What do you think?

**Comment by jarodreyes** [comment]
:+1:
