### ISSUE TITLE
Content Improvement Suggestions

### ISSUE THREAD

**Issue by dprothero** [TwilioDevEd/employee-directory-rails#8]
Here are some suggestions for improving the narrative for this already great tutorial:

1. First step is a little long. We should shoot for getting the majority, if not the entirety, of the most important content within the size of the tutorial container on twilio.com. I usually resize my browser to test this. I think the high level overview can be trimmed down and made more concise. (This was the first feedback I received on my first step as well... you can take a look at the C# tutorial for the outcome of that feedback.)

2. I think the second step "Setting Up the SMS Web Hook" can probably be eliminated. We give detailed instructions in the README file of the code to do this. The narrative should focus on the use case.

3. Step 3 is great. Concise and is talking about the use case and letting the code speak for itself.

4. Step 4 is good, but I'd think about a different title instead of "Exact Match"... Perhaps something that is more descriptive of our use case... maybe "Matching an Employee Exactly" or something along those lines.

5. Same with steps 5 and 6. They need more use case centric titles.

6. +1 for using Fuzzily. Now I want to update the C# tutorial with a fuzzy matching routine!

7. On step 7 (Storing Suggestions With Cookies) I think can use a different title as well. In addition, I would shorten the narrative here. I think the code does most of the talking here. You just need to explain we're using cookies to remember the options for subsequent requests from the same user.

That's all I've got. My apologies if this is rather long winded, but this is my first tutorial review. :)

**Comment by acamino** [comment]
@dprothero thanks for the feedback, I'll really appreciate it. We'll update the tutorial accordingly. As soon as we'll have an updated version I'll ping you to take a look on that one.

BTW it's a great review. :smiley:

**Comment by mcelicalderon** [comment]
@dprothero please take a look at https://github.com/TwilioDevEd/employee-directory-rails/commit/2986e7e30d62f50691bc56bbd2ea1dbfda4c0154

This addresses the suggested changes but let me know what you think about those. Thanks!

**Comment by dprothero** [comment]
@mcelicalderon Step 6 (second to last) has a "More on Twilio Cookies!" link but it goes to the same place as the Twilio Cookies link. Was this intentional?

**Comment by mcelicalderon** [comment]
@dprothero Yes, it was intentional. Do you think we should remove one of them?

**Comment by dprothero** [comment]
Yes, I think the extra link at the bottom is redundant. Thanks!

**Comment by mcelicalderon** [comment]
Done! Here: 2044f2a296a6c815ec3f27b98a2095dae91b5242

**Comment by dprothero** [comment]
+1
